package com.ultrader.bot.util;

/**
 * Enum of Settings
 * @author ytx1991
 */
public enum SettingConstant {
    ALPACA_KEY_NAME("KEY_ALPACA_KEY"),
    ALPACA_SECRET_NAME("KEY_ALPACA_SECRET"),
    ALPACA_PAPER_KEY_NAME("KEY_ALPACA_PAPER_KEY"),
    ALPACA_PAPER_SECRET_NAME("KEY_ALPACA_PAPER_SECRET"),
    BOT_KEY_NAME("KEY_ULTRADER_KEY"),
    BOT_SECRET_NAME("KEY_ULTRADER_SECRET"),
    TRADING_PLATFORM_NAME("GLOBAL_TRADING_PLATFORM"),
    WHITE_LIST_ENABLE_NAME("TRADE_WHITE_LIST_ENABLE"),
    TRADE_STOCK_LIST_NAME("TRADE_STOCK_LIST"),
    TRADE_EXCHANGE_NAME("TRADE_EXCHANGE_LIST"),
    MARKET_DATA_PLATFORM_NAME("GLOBAL_MARKETDATA_PLATFORM"),
    INDICATOR_MAX_LENGTH("INDICATOR_MAX_LENGTH"),
    TRADE_PERIOD_SECOND("TRADE_PERIOD_SECOND"),
    AUTO_TRADING_ENABLE("GLOBAL_AUTO_TRADING_ENABLE"),
    TRADE_PRICE_LIMIT_MAX("TRADE_PRICE_LIMIT_MAX"),
    TRADE_PRICE_LIMIT_MIN("TRADE_PRICE_LIMIT_MIN"),
    TRADE_VOLUME_LIMIT_MAX("TRADE_VOLUME_LIMIT_MAX"),
    TRADE_VOLUME_LIMIT_MIN("TRADE_VOLUME_LIMIT_MIN"),
    TRADE_BUY_MAX_LIMIT("TRADE_BUY_MAX_LIMIT"),
    TRADE_BUY_HOLDING_LIMIT("TRADE_BUY_HOLDING_LIMIT"),
    TRADE_BUY_STRATEGY("TRADE_BUY_STRATEGY"),
    TRADE_SELL_STRATEGY("TRADE_SELL_STRATEGY");

    public static final String DELIMITER = ",";
    private String name;

    SettingConstant(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }
}
