export const ADD_SETTING = 'ADD_SETTING';
export const GET_SETTINGS_SUCCESS = 'GET_SETTINGS_SUCCESS';

export const ADD_CONDITIONAL_SETTING = 'ADD_CONDITIONAL_SETTING';
export const GET_CONDITIONAL_SETTINGS_SUCCESS = 'GET_CONDITIONAL_SETTINGS_SUCCESS';