export const GET_STRATEGIES_SUCCESS = 'GET_STRATEGIES_SUCCESS';
export const DELETE_STRATEGY_SUCCESS = 'DELETE_STRATEGY_SUCCESS';
export const ADD_STRATEGY_SUCCESS = 'ADD_STRATEGY_SUCCESS';
export const EDIT_STRATEGY_SUCCESS = 'EDIT_STRATEGY_SUCCESS';
