export const GET_RULES_SUCCESS = 'GET_RULES_SUCCESS';
export const ADD_RULE_SUCCESS = 'ADD_RULE_SUCCESS';
export const EDIT_RULE_SUCCESS = 'EDIT_RULE_SUCCESS';
export const DELETE_RULE_SUCCESS = 'DELETE_RULE_SUCCESS';