export const GET_ASSET_LISTS_SUCCESS = 'GET_ASSET_LISTS_SUCCESS';
export const ADD_ASSET_LIST_SUCCESS = 'ADD_ASSET_LIST_SUCCESS';
export const EDIT_ASSET_LIST_SUCCESS = 'EDIT_ASSET_LIST_SUCCESS';
export const DELETE_ASSET_LIST_SUCCESS = 'DELETE_ASSET_LIST_SUCCESS';
export const GET_ALL_ASSETS_SUCCESS = 'GET_ALL_ASSETS_SUCCESS';