export const CONNECTED_TO_MONITOR = 'CONNECTED_TO_MONITOR';
export const RECEIVED_MONITOR_MESSAGE = 'RECEIVED_MONITOR_MESSAGE';
export const RETRIEVED_RULE_TYPES = 'RETRIEVED_RULE_TYPES';
export const RETRIEVED_INDICATOR_TYPES = 'RETRIEVED_INDICATOR_TYPES';
export const RETRIEVED_INDICATOR_CATEGORIES = 'RETRIEVED_INDICATOR_CATEGORIES';
export const RETRIEVED_CATEGORY_INDICATOR_MAP = 'RETRIEVED_CATEGORY_INDICATOR_MAP';
export const RETRIEVED_STRATEGY_METADATA = 'RETRIEVED_STRATEGY_METADATA';
