export const CONNECTED_TO_MONITOR = 'CONNECTED_TO_MONITOR';
export const RECEIVED_MONITOR_MESSAGE = 'RECEIVED_MONITOR_MESSAGE';
export const RECEIVED_DATA_STATUS_MESSAGE = 'RECEIVED_DATA_STATUS_MESSAGE';
export const RECEIVED_MARKET_STATUS_MESSAGE = 'RECEIVED_MARKET_STATUS_MESSAGE';
export const RECEIVED_BOT_STATUS_MESSAGE = 'RECEIVED_BOT_STATUS_MESSAGE';

export const RECEIVED_PORTFOLIO_MONITOR_MESSAGE = 'RECEIVED_PORTFOLIO_MONITOR_MESSAGE';
export const RECEIVED_TRADES_MONITOR_MESSAGE = 'RECEIVED_TRADES_MONITOR_MESSAGE';
export const RECEIVED_PROFIT_MONITOR_MESSAGE = 'RECEIVED_PROFIT_MONITOR_MESSAGE';
export const RECEIVED_PERFORMANCE_MONITOR_MESSAGE = 'RECEIVED_PERFORMANCE_MONITOR_MESSAGE';

export const RETRIEVED_RULE_TYPES = 'RETRIEVED_RULE_TYPES';
export const RETRIEVED_INDICATOR_TYPES = 'RETRIEVED_INDICATOR_TYPES';
export const RETRIEVED_INDICATOR_CATEGORIES = 'RETRIEVED_INDICATOR_CATEGORIES';
export const RETRIEVED_CATEGORY_INDICATOR_MAP = 'RETRIEVED_CATEGORY_INDICATOR_MAP';
export const RETRIEVED_STRATEGY_METADATA = 'RETRIEVED_STRATEGY_METADATA';

export const RETRIEVED_DASHBOARD_NOTIFICATIONS = 'RETRIEVED_DASHBOARD_NOTIFICATIONS';