export const OPTIMIZATION_SUCCESS = 'OPTIMIZATION_SUCCESS';
export const RECEIVED_OPTIMIZATION_PROGRESS_MESSAGE = 'RECEIVED_OPTIMIZATION_PROGRESS_MESSAGE';
export const OPTIMIZATION_STARTED = 'OPTIMIZATION_STARTED';

